### ISSUE TITLE
Trouble to run the demo

### ISSUE THREAD

**Issue by antoine-guillou** [stefaneidelloth/javafx-d3#5]
I don't manage to execute the demo properly. I don't have a lot of experience with maven, so I may well do something wrong.

What I did:
I executed `mvn clean install` in both javafx-d3 and javafx-d3-demo.
I says BUILD SUCCESS in both case, without any errors.
But then javafx-d3-demo/target only contains the antrun directory, no jar file.

**Comment by stefaneidelloth** [comment]
What IDE are you using? (Or just command line?)
I use Eclipse with the Maven plugin M2E. 
After updating the Maven projects (Alt+F5) I can start the demo with right click
on org.treez.javafxd3.d3.JavaFxD3DemoSuite and choosing RunAs Java Application.

For the pom file of the demo there are two main options:

a) Use pom packaging and include the core project javafx-d3 as a module. If the pom of the demo project is executed, the core project will also be executed.   

b) Use jar packaging and include the core project javafx-d3 only as a dependency. As a prerequisite for running the demo pom file, the core pom file has to be executed before. 

Since there were issues with b) I switched to a).

**Comment by antoine-guillou** [comment]
I am usually using netbeans, but I also tried with the command line.

I just tried with eclipse Mars and M2E plugin.
I manage to add the 2 maven projects but they don't build because: Project 'javafx-d3' is missing required source folder: 'test/resources'

**Comment by antoine-guillou** [comment]
I added the folder manually and it works!
Thank you, I will have a look at the demo.

**Comment by stefaneidelloth** [comment]
Thank you for your feedback. I added the folders and also adapted toe pom to create some jars.
